name: Go

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v `go list ./...`
